# Generated by Django 6.0.3 on 2026-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_stuimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StuEmail',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
